### ISSUE TITLE
Very excited

### ISSUE THREAD

**Issue by adriatic** [stormpath/loopback-stormpath#2]
I believe that written issues should go way ahead of just bug reports. Not only that I want to add accolades, I want to start with sharing my mind even before touching this code and a few seconds after I read this [announcement that just arrived to my mailbox](https://stormpath.com/blog/introducing-loopback-support/?utm_source=email%20newsletter&utm_medium=email&utm_campaign=ui%20security%20webinar&utm_content=grid%201%20text)

For about a month I am trying to think of a way to get Stormpath team to recognize something that is very obvious to me: **Authentication & User Management API** is a service that needs to be planned for before even starting to write a world class application (speaking as an app developer here), meaning that Authentication & User Management API service provider ought to be able to offer guidance to their customer that reached far beyond code snippets that show how access to some API should be allowed only to folks with this specific role.

As I did not see much impact from my several support posts like [this](https://support.stormpath.com/hc/en-us/requests/2979) I decided to make the real case that illustrates the real need for an integration of precisely the type you just did. Please check my [blog](http://blog.congral.com/2015/05/02/to-genereate-or-to-not-generate/) as well as the forum topics [Server Side Application Structure](http://blog.congral.com/forums/topic/server-side-application-structure/), [Client Side Application Structure](http://blog.congral.com/forums/topic/client-side-application-structure/) and [Common Infrastructure](http://blog.congral.com/forums/topic/common-infrastructure-2/). Then realize that all this was written without me knowing anything about Strongloop at all - and you should appreciate the size of the overlap you and I have without knowing that.

However the most exciting piece is the simplicity and elegance of this StrongLoop <----> Stormpath integration. With a few characters changed in a couple of JSON files you swapped out the whole massive "user thing" from StrongLoop and plopped it where it rightfully belongs (in Stormpath's care). **This is also a big atta-boy to Strongloop architecture, let's not forget that.**

I dare to say that you do not have the right assessment of the value of what you did here - you need to be app architect to fully appreciate this. I am that guy and I do appreciate this!!

**Comment by rdegges** [comment]
Thanks for the awesome comment! Since you wrote this we've spoken through email threads, but I wanted to post an update here for any readers who might stumble across this issue.

@adriatic is going to be helping with the improvements on this library in the near future, and will be collaborating with us to make this project super awesome and feature-complete.

Looking forward to working with you!

(Closing this ticket out for now, since there are no action items.)
